name: Chhelp publish
on:
  push:
    branches:
      - main
jobs:
  release:
    name: publish
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js version 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org
      - name: install packages and build
        run: npm ci
      - name: publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
